# Generated by Django 3.0.4 on 2020-04-20 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserLogin', models.CharField(max_length=40, verbose_name='ФИО мастера')),
                ('cardNumber', models.BigIntegerField(unique=True, verbose_name='Номер Карты')),
                ('accessLevel', models.PositiveSmallIntegerField(verbose_name='Уровень доступа')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Rubric', verbose_name='Участок')),
            ],
            options={
                'verbose_name_plural': 'Список Мастеров',
                'ordering': ['published'],
            },
        ),
    ]
