# Generated by Django 3.0.5 on 2020-05-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='cardNumber',
            field=models.BigIntegerField(verbose_name='Номер Карты'),
        ),
    ]
