# Generated by Django 3.0.5 on 2020-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20200512_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='id',
        ),
        migrations.AlterField(
            model_name='masters',
            name='cardNumber',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер Карты'),
        ),
    ]
