# Generated by Django 3.0.5 on 2020-05-13 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bboard', '0003_auto_20200514_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(db_column='eventName', max_length=30)),
            ],
            options={
                'db_table': 'eventev',
            },
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('linename', models.CharField(db_column='lineName', max_length=20)),
            ],
            options={
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('diename', models.CharField(db_column='dieName', max_length=50)),
                ('eventval0', models.CharField(db_column='eventVal0', max_length=16)),
                ('eventval1', models.CharField(db_column='eventVal1', max_length=16)),
                ('eventtime', models.DateTimeField(db_column='EventTime', primary_key=True, serialize=False)),
                ('eventid', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.PROTECT, to='changestory.EventEv')),
                ('lineid', models.ForeignKey(db_column='line_id', on_delete=django.db.models.deletion.PROTECT, to='changestory.Lines')),
                ('masterid', models.ForeignKey(db_column='master_id', on_delete=django.db.models.deletion.PROTECT, to='bboard.masters')),
            ],
            options={
                'db_table': 'presentations',
                'ordering': ['-eventtime'],
            },
        ),
    ]
