# Generated by Django 3.2.8 on 2023-06-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changestory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentations',
            options={},
        ),
    ]
