# Generated by Django 3.0.5 on 2020-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('diename', models.CharField(db_column='dieName', max_length=20)),
                ('tolerancem', models.FloatField(blank=True, db_column='toleranceM', null=True)),
                ('actualthickness', models.FloatField(blank=True, db_column='actualThickness', null=True)),
                ('tolerancep', models.FloatField(blank=True, db_column='toleranceP', null=True)),
                ('measuringerror', models.BooleanField(blank=True, db_column='measuringError', null=True)),
                ('eventtime', models.DateTimeField(db_column='EventTime')),
            ],
            options={
                'db_table': 'thickness',
                'managed': False,
            },
        ),
    ]
